### ISSUE TITLE
Implement cart state

### ISSUE THREAD

**Issue by RedBlueKoi** [RedBlueKoi/keyworld-react#11]

**Comment by spartanny** [comment]
Do we mean redux state here ? Actions will be dispatched when customer selects/ removes some product for checkout .
I am thinking to create a map with key to uniquely identify some product and value to be a object 
```
{
  "unique-product-identifier-1" : {
    name,
    price,
    quantity,
    imageURL,
  }
  ...
}
```
for list of actions:

- add qty
- remove qty
- remove product (delete)

**Comment by RedBlueKoi** [comment]
Yeah, just a Redux slice. We are using TS, so all we need here is just an interface which gonna represent the API response. In out case the current data structure looks something like this:
```js
interface Product: {
  category: string
  description: string
  images: string[]
  name: string
  perks: Perks
}
interface Perks: {
  ANSI: boolean
  ISO: boolean
  QMK: boolean
  VIA: boolean
  material: string
  splitSpacebar: boolean
  weight: string
  price: number
  type: string
}
```
