### ISSUE TITLE
Set up pages

### ISSUE THREAD

**Issue by RedBlueKoi** [RedBlueKoi/keyworld-react#6]
For now we have
- Homepage
- Category Page
- Product Page
- Checkout Page
- Success Page
- 404

**Comment by RedBlueKoi** [comment]
@spartanny Please remember to link PR to the issue if you create your branch manually

**Comment by spartanny** [comment]
Oh okay ! Will do that .

**Comment by RedBlueKoi** [comment]
I just realised that there are few problems with this PR we merged. Could you please fix them and create a new PR?
Things to fix:
- Lint all the files
- Fix routes for category and a product. These routes should be dynamic

Example: /category/:categoryUrl for category page

**Comment by spartanny** [comment]
for the dynamic routing do we require to redirect to a new view altogether or reuse the original view for product and category page respectively
